"""create_notification_settings

Revision ID: dd9ee537ca30
Revises: 4216d2553ee8
Create Date: 2026-07-08 13:26:57.290189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9ee537ca30'
down_revision: Union[str, Sequence[str], None] = '4216d2553ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_uploaded', sa.JSON(), nullable=True),
    sa.Column('transcript_ready', sa.JSON(), nullable=True),
    sa.Column('ai_summary_ready', sa.JSON(), nullable=True),
    sa.Column('kg_ready', sa.JSON(), nullable=True),
    sa.Column('action_items_ready', sa.JSON(), nullable=True),
    sa.Column('failed_processing', sa.JSON(), nullable=True),
    sa.Column('calendar_sync', sa.JSON(), nullable=True),
    sa.Column('oauth_expired', sa.JSON(), nullable=True),
    sa.Column('weekly_reports', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
