"""create_ai_preferences

Revision ID: 9029c3411dea
Revises: 96464203b161
Create Date: 2026-07-08 13:26:46.983798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9029c3411dea'
down_revision: Union[str, Sequence[str], None] = '96464203b161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_provider', sa.String(length=50), nullable=True),
    sa.Column('fallback_provider', sa.String(length=50), nullable=True),
    sa.Column('preferred_model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('summary_length', sa.String(length=50), nullable=True),
    sa.Column('response_style', sa.String(length=50), nullable=True),
    sa.Column('enable_chat_memory', sa.Boolean(), nullable=True),
    sa.Column('enable_semantic_search', sa.Boolean(), nullable=True),
    sa.Column('enable_context_retrieval', sa.Boolean(), nullable=True),
    sa.Column('enable_kg_generation', sa.Boolean(), nullable=True),
    sa.Column('enable_speaker_intelligence', sa.Boolean(), nullable=True),
    sa.Column('enable_automatic_insights', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_preferences')
    # ### end Alembic commands ###
