"""create_risks

Revision ID: 90fc008fa8b1
Revises: b31d10d7f66e
Create Date: 2026-07-08 13:27:02.724939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fc008fa8b1'
down_revision: Union[str, Sequence[str], None] = 'b31d10d7f66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('risk_text', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risks')
    # ### end Alembic commands ###
