"""create_meetings

Revision ID: 82e13e6e8c7a
Revises: 722cd02ce0e5
Create Date: 2026-07-08 13:26:41.917432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e13e6e8c7a'
down_revision: Union[str, Sequence[str], None] = '722cd02ce0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='UPLOADED', nullable=True),
    sa.Column('ai_status', sa.String(length=50), server_default='PENDING', nullable=True),
    sa.Column('embedding_status', sa.String(length=50), server_default='PENDING', nullable=True),
    sa.Column('speaker_status', sa.String(length=50), server_default='PENDING', nullable=True),
    sa.Column('kg_status', sa.String(length=50), server_default='PENDING', nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('one_minute_read', sa.Text(), nullable=True),
    sa.Column('followup_email', sa.Text(), nullable=True),
    sa.Column('sentiment_summary', sa.Text(), nullable=True),
    sa.Column('agenda_items', sa.JSON(), nullable=True),
    sa.Column('technical_context', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('key_themes', sa.JSON(), nullable=True),
    sa.Column('main_takeaways', sa.JSON(), nullable=True),
    sa.Column('important_quotes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###
