"""create_storage_usage

Revision ID: 79ad3e8df71c
Revises: 97af18a10adc
Create Date: 2026-07-08 13:27:05.385936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "79ad3e8df71c"
down_revision: Union[str, Sequence[str], None] = "97af18a10adc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("recordings_bytes", sa.Float(), nullable=True),
        sa.Column("transcripts_bytes", sa.Float(), nullable=True),
        sa.Column("kg_bytes", sa.Float(), nullable=True),
        sa.Column("embeddings_bytes", sa.Float(), nullable=True),
        sa.Column("reports_bytes", sa.Float(), nullable=True),
        sa.Column("chat_bytes", sa.Float(), nullable=True),
        sa.Column("total_limit_bytes", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storage_usage")
    # ### end Alembic commands ###
