"""create_user_security_settings

Revision ID: f44e80f7e819
Revises: 86a446d2455a
Create Date: 2026-07-08 13:27:09.365242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f44e80f7e819"
down_revision: Union[str, Sequence[str], None] = "86a446d2455a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_security_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=True),
        sa.Column("two_factor_secret", sa.String(length=255), nullable=True),
        sa.Column("backup_codes", sa.JSON(), nullable=True),
        sa.Column("security_notifications", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_security_settings")
    # ### end Alembic commands ###
