"""create_meeting_preferences

Revision ID: 104e4d8aba98
Revises: 3482afa0e103
Create Date: 2026-07-08 13:26:54.668344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104e4d8aba98'
down_revision: Union[str, Sequence[str], None] = '3482afa0e103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_language', sa.String(length=50), nullable=True),
    sa.Column('enable_speaker_id', sa.Boolean(), nullable=True),
    sa.Column('enable_translation', sa.Boolean(), nullable=True),
    sa.Column('enable_subtitles', sa.Boolean(), nullable=True),
    sa.Column('transcript_format', sa.String(length=50), nullable=True),
    sa.Column('default_category', sa.String(length=100), nullable=True),
    sa.Column('recording_retention_days', sa.Integer(), nullable=True),
    sa.Column('auto_delete_recordings', sa.Boolean(), nullable=True),
    sa.Column('meeting_privacy', sa.String(length=50), nullable=True),
    sa.Column('default_share_settings', sa.JSON(), nullable=True),
    sa.Column('auto_import_meetings', sa.Boolean(), nullable=True),
    sa.Column('auto_import_recordings', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_transcript', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_summary', sa.Boolean(), nullable=True),
    sa.Column('auto_create_action_items', sa.Boolean(), nullable=True),
    sa.Column('auto_create_risks', sa.Boolean(), nullable=True),
    sa.Column('auto_create_kg', sa.Boolean(), nullable=True),
    sa.Column('auto_create_tech_analysis', sa.Boolean(), nullable=True),
    sa.Column('auto_create_decisions', sa.Boolean(), nullable=True),
    sa.Column('calendar_sync_frequency', sa.String(length=50), nullable=True),
    sa.Column('recording_preference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_preferences')
    # ### end Alembic commands ###
